Repository wecode-bootcamp-korea/32-1st-Posea-frontend, pull requests merged in 2022-05, with the labels that each got.

#3 [32기 김현수] 목데이터 활용해 nav 레이아웃 및 기능 구현
  public/data/navListData.json
  public/images/navBodyHand.jpg
  public/images/navHair.jpg
  public/images/navSkinCare.jpg
  src/Router.js
  src/components/Nav/GnbItem/GnbItem.js
  src/components/Nav/GnbItem/GnbItem.scss
  src/components/Nav/GnbItemContent/GnbItemContent.js
  src/components/Nav/GnbItemContent/GnbItemContent.scss
  src/components/Nav/GnbItemContentMenu/GnbItemContentMenu.js
  src/components/Nav/GnbItemContentMenu/GnbItemContentMenu.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Main/Main.js
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#4 [posea-이하영] Add:로그인 회원가입 기능구현 중
  src/components/Nav/Nav.js
  src/pages/Login/Checkboxes/Checkboxes.js
  src/pages/Login/Checkboxes/Checkboxes.scss
  src/pages/Login/FormLayout/FormLayout.js
  src/pages/Login/FormLayout/FormLayout.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/userMessage.js
Labels: Status: 추가 기능 구현중, Status: 수정 요청

#8 [Pösea - 김현수] nav 스타일 및 기능 추가
  src/components/Nav/GnbItem/GnbItem.js
  src/components/Nav/GnbItemContent/GnbItemContent.js
  src/components/Nav/GnbItemContent/GnbItemContent.scss
  src/components/Nav/GnbItemContentMenu/GnbItemContentMenu.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Login/Login.scss
Labels: Status: 추가 기능 구현중

#6 [posea-김현수] 상품 리스트 페이지 구현
  public/data/productsListData.json
  public/images/1.png
  public/images/2.png
  public/images/3.png
  public/images/4.png
  public/images/5.png
  src/Router.js
  src/pages/ProductsList/CarouselBtns/CarouselBtns.js
  src/pages/ProductsList/CarouselBtns/CarouselBtns.scss
  src/pages/ProductsList/CarouselIntro/CarouselIntro.js
  src/pages/ProductsList/CarouselIntro/CarouselIntro.scss
  src/pages/ProductsList/CarouselItem/CarouselItem.js
  src/pages/ProductsList/CarouselItem/CarouselItem.scss
  src/pages/ProductsList/CarouselList/CarouselList.js
  src/pages/ProductsList/CarouselList/CarouselList.scss
  src/pages/ProductsList/ProductsCarousel/ProductsCarousel.js
  src/pages/ProductsList/ProductsCarousel/ProductsCarousel.scss
  src/pages/ProductsList/ProductsList.js
  src/pages/ProductsList/ProductsList.scss
  src/pages/ProductsList/ProductsLnb/ProductsLnb.js
  src/pages/ProductsList/ProductsLnb/ProductsLnb.scss
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#2 [posea - 이나연] 3차 리뷰 수정완료
  public/data/carouselData.json
  public/data/infoRight.json
  public/data/modalInfo.json
  public/data/productInfo.json
  public/data/usageInfo.json
  src/Router.js
  src/pages/Details/Carousel/Carousel.js
  src/pages/Details/Carousel/Carousel.scss
  src/pages/Details/Details.js
  src/pages/Details/Details.scss
  src/pages/Details/InfoDetails/InfoDetails.js
  src/pages/Details/InfoDetails/InfoDetails.scss
  src/pages/Details/InfoDetailsContent/InfoDetailsContent.js
  src/pages/Details/InfoDetailsContent/InfoDetailsContent.scss
  src/pages/Details/InfoRight/InfoRight.js
  src/pages/Details/InfoTitle/InfoTitle.js
  src/pages/Details/InfoUsage/InfoUsage.js
  src/pages/Details/InfoUsageContent/InfoUsageContent.js
  src/pages/Details/Modal/Modal.js
  src/pages/Details/Modal/Modal.scss
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#7 [Posea - 유동혁] Cart 컴포넌트 UI 및 기능 구현
  src/components/Cart/CART_ITEMS.js
  src/components/Cart/Cart.js
  src/components/Cart/Cart.scss
  src/components/Cart/CartItem/CartItem.js
  src/components/Cart/CartItem/CartItem.scss
  src/components/Cart/CartItemHeader/CartItemHeader.js
  src/components/Cart/CartItemHeader/CartItemHeader.scss
  src/components/Cart/CartItems/CartItems.js
  src/components/Cart/CartItems/CartItems.scss
  src/components/Cart/CartSummary/CartSummary.js
  src/components/Cart/CartSummary/CartSummary.scss
  src/components/Cart/angleDown.svg
Labels: Status: 추가 기능 구현중, Status: 수정 요청
